NDEV-1842 compatibility with neon api axum (#25)
* eth_getBlockByHash: add details to log

* fix message

* set naon-apt latest

* update

* uncomment response

* fix last commit

* cargo update

* add debug info

* fix logs

* update tests

* fix get_balance test

* fix eth_call test

* set sleep(60) to tests

* fix tests

* add def value to get_balance, get_tracsaction_count, get_code

* fix last commit

* fix get_storage_at, get_balance, reduce logs

* fix last commit

* cargo update

* CI workflow affect build result, disable some tests, set neon-api to axum

* replace neon_api:latest to neon_api:4782b7290a6e0d30b8bb319f5ac2a7894dd073ff

* fix last commit

* uncomment tests

* debug  NeonApiError deserialize error

* fix last commit

* disable trace functionality

* rollback deserialize debug info

* update docker-compose: neon-api without tracing (f695c622fb7114932026c457dfbb88194d767ed5)

* Revert "rollback deserialize debug info"

This reverts commit 641ac04fe9860c481f19f935016e0960cb31fbfb.

* update neon-api

* remove Raw response print, change type id u16-u32

* update cargo.lock

* impl request_id as Atomic64

* small fix

* update Cargo.toml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -63,12 +63,23 @@ jobs:
         run: docker-compose -f docker-compose-test.yml pull
 
       - name: Up neon-tracer-test
-        run: docker-compose -f docker-compose-test.yml up neon-tracer-test --quiet-pull
+        run: docker-compose -f docker-compose-test.yml up --exit-code-from neon-tracer-test neon-tracer-test --quiet-pull
 
       - name: Dump docker logs
         uses: jwalton/gh-docker-logs@v2
         with:
           dest: './logs'
+
+      - name: Parse tests results
+        run: |
+          if grep "FAIL" ./logs/neon-tracer-test.log
+          then
+            echo "Tests finished with errors";
+            exit 1;
+          else
+            echo "Tests completed successfully";
+          fi
+
       - name: Tar logs
         run: tar cvzf ./logs.tgz ./logs
       - name: Upload logs to GitHub
